{
 "title": "Tag.ly Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "ShoutOut BT - Mentions Per Minute (Top Stocks)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ORGANIZATION) (tagly_mentions_per_minute)",
     "legendFormat": "{{ORGANIZATION}}"
    }
   ]
  },
  {
   "title": "Orders Placed (By region)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (region) (tagly_calls_per_minute)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Orders Placed (Top Stocks)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stock) (tagly_calls_per_minute)",
     "legendFormat": "{{stock}}"
    }
   ]
  },
  {
   "title": "Order Place BT - Errors Per Minute (Region)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (region) (tagly_errors_per_minute)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Order Place BT - Errors Per Minute (Top Stocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (stock) (tagly_errors_per_minute)",
     "legendFormat": "{{stock}}"
    }
   ]
  },
  {
   "title": "Order Place BT Latency (By region)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (region) (tagly_request_latency_ms)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Order Place BT Latency (Top Stocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (stock) (tagly_request_latency_ms)",
     "legendFormat": "{{stock}}"
    }
   ]
  },
  {
   "title": "Exceptions in Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{compose_service=\"order-processor\"} |~ \"exception\""
    }
   ]
  }
 ]
}